# Generated by Django 5.1.3 on 2024-11-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_sliderimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'ordering': ['order'], 'verbose_name': 'Изображение слайдера', 'verbose_name_plural': 'Изображения слайдера'},
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Порядок'),
        ),
    ]
